development:
  DB_HOSTNAME: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: skeleton
  DB_PORT: 5432
test:
  DB_HOSTNAME: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: skeleton_test
  DB_PORT: 5432